# Daily snapshot policy for the data disk. Snapshots inherit the
# source disk's CMEK setting automatically — when enable_cmek=true
# the snapshot is encrypted with the same key #7 declared.
#
# Boot disk is NOT covered: it's regenerated by terraform from the
# COS image on every VM rebuild and holds no state worth backing up.
# Only the data disk (/var/lib/voitta) carries the SQLite db, CAS,
# Qdrant, model cache, and Caddy ACME state.

resource "google_compute_resource_policy" "data_daily_snapshot" {
  name   = "${local.prefix}-data-daily"
  region = var.region

  snapshot_schedule_policy {
    schedule {
      daily_schedule {
        days_in_cycle = 1
        # GCP wants HH:MM:00 in UTC. Format the var as a 2-digit hour.
        start_time = format("%02d:00", var.snapshot_hour)
      }
    }

    retention_policy {
      max_retention_days    = var.snapshot_retention_days
      on_source_disk_delete = "KEEP_AUTO_SNAPSHOTS"
    }

    snapshot_properties {
      labels            = var.labels
      storage_locations = [var.region]
      # No explicit encryption_key here: the snapshot inherits the
      # source disk's CMEK config when enable_cmek=true, otherwise
      # falls back to Google-managed encryption. Customer-supplied
      # snapshot keys are out of scope.
    }
  }
}

# Wire the policy onto the data disk. boot_disk doesn't get one.
resource "google_compute_disk_resource_policy_attachment" "data" {
  name = google_compute_resource_policy.data_daily_snapshot.name
  disk = google_compute_disk.data.name
  zone = var.zone
}
